export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const VITAMIN_ROUTE = '/vitamin'
